OPTIONS(SKIP=1, DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
INFILE      '-'
TRUNCATE
INTO TABLE TEST_SQL_LOADER
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
    VAR1    CHAR(3),
    VAR2    CHAR(4),
    VAR3    CHAR(5)
)

