OPTIONS(SKIP=1, DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
INFILE      './input/test_sql_loader.csv'
TRUNCATE
INTO TABLE NO_SUCH_TABLE
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
    VAR1    CHAR(3),
    VAR2    CHAR(4),
    VAR3    CHAR(5)
)


